SLOT_0_NORMAL_SHOT       = $0203e0
SLOT_1_PHASER_SHELL      = $0203ea
SLOT_2_BUBBLE_PROJECTILE = $0203fe
SLOT_3_3_WAY_SHOT        = $020408
SLOT_4_EXPLOSIVES        = $02041c

OFFSET_WEAPON_ICON       = 8

ICON_NORMAL_SHOT         = $6526
ICON_PHASER_SHELL        = $656e
ICON_BUBBLE_PROJECTILE   = $655c
ICON_3_WAY_SHOT          = $6580
ICON_EXPLOSIVES          = $654a

    org 0
    incbin "ghostbusters.md"

    org OFFSET_WEAPON_ICON + SLOT_1_PHASER_SHELL
            dw      ICON_EXPLOSIVES

    org OFFSET_WEAPON_ICON + SLOT_2_BUBBLE_PROJECTILE
            dw      ICON_PHASER_SHELL

    org OFFSET_WEAPON_ICON + SLOT_4_EXPLOSIVES
            dw      ICON_BUBBLE_PROJECTILE
